-- 1. Detectar las tablas y las FK con el campus camp_code
SELECT x.TABLE_NAME, y.constraint_name
FROM DBA_TAB_COLUMNS x, dba_constraints y 
WHERE x.column_name LIKE '%CAMP_CODE%'
and x.table_name=y.table_name
and y.constraint_type='R'
order by table_name;

-- 2. Script que permite desahabilitar las FK de todas las tablas que cumplan las condiciones
SELECT 'ALTER TABLE ' ||x.owner||'.'|| x.TABLE_NAME || ' disable constraint ' || y.constraint_name ||';'
FROM DBA_TAB_COLUMNS x, dba_constraints y 
WHERE x.column_name LIKE '%CAMP_CODE%'
and x.table_name='SARADAP'
and x.table_name=y.table_name
and y.constraint_type='R'
order by x.table_name;

ALTER TABLE saturn.SARAPPD disable constraint FK1_SARAPPD_INV_SARADAP_KEY;
ALTER TABLE SATURN.SARCHKL disable constraint FK1_SARCHKL_INV_SARADAP_KEY;
ALTER TABLE SATURN.SARCHRT disable constraint FK1_SARCHRT_INV_SARADAP_KEY;
alter table saturn.SARQUAN disable constraint FK1_SARQUAN_INV_SARADAP_KEY;
ALTER TABLE SATURN.SRRLEND disable constraint FK1_SRRLEND_INV_SRBRECR_KEY;
ALTER TABLE SATURN.SRRRSRC DISABLE CONSTRAINT FK1_SRRRSRC_INV_SRBRECR_KEY;
ALTER TABLE SATURN.SRRCHRT DISABLE CONSTRAINT FK1_SRRCHRT_INV_SRBRECR_KEY;
ALTER TABLE SATURN.SHRDGIH DISABLE CONSTRAINT FK1_SHRDGIH_INV_SHRDGMR_KEY;
ALTER TABLE SATURN.SHRDGCM DISABLE CONSTRAINT FK1_SHRDGCM_INV_SHRDGMR_KEY;
ALTER TABLE SATURN.SHBDIPL DISABLE CONSTRAINT FK1_SHBDIPL_INV_SHRDGMR_KEY;
ALTER TABLE SATURN.SIRASGN DISABLE CONSTRAINT FK1_SIRASGN_INV_SSBSECT_KEY;
ALTER TABLE SATURN.SSRLINK DISABLE CONSTRAINT FK1_SSRLINK_INV_SSBSECT_KEY;
ALTER TABLE SATURN.SSRRTST DISABLE CONSTRAINT FK1_SSRRTST_INV_SSBSECT_KEY;
ALTER TABLE SATURN.SSRRMAJ DISABLE CONSTRAINT FK1_SSRRMAJ_INV_SSBSECT_KEY;
ALTER TABLE SATURN.SSRTEXT DISABLE CONSTRAINT FK1_SSRTEXT_INV_SSBSECT_KEY;
ALTER TABLE SATURN.SSRCORQ DISABLE CONSTRAINT FK1_SSRCORQ_INV_SSBSECT_KEY;
ALTER TABLE SATURN.SSRRCOL DISABLE CONSTRAINT FK1_SSRRCOL_INV_SSBSECT_KEY;
ALTER TABLE SATURN.SSRRLVL DISABLE CONSTRAINT FK1_SSRRLVL_INV_SSBSECT_KEY;
ALTER TABLE SATURN.SSRSPRT DISABLE CONSTRAINT FK1_SSRSPRT_INV_SSBSECT_KEY;
ALTER TABLE GENERAL.GVRSRVY DISABLE CONSTRAINT FK21_GVRSRVY_INV_SSBSECT_KEY;
ALTER TABLE SATURN.SSRRCLS DISABLE CONSTRAINT FK1_SSRRCLS_INV_SSBSECT_KEY;
ALTER TABLE SATURN.SSRRATT DISABLE CONSTRAINT FK1_SSRRATT_INV_SSBSECT_KEY;
alter table saturn.ssrrdep disable constraint FK1_SSRRDEP_INV_SSBSECT_KEY;
ALTER TABLE SATURN.SSRRCHR disable constraint FK1_SSRRCHR_INV_SSBSECT_KEY;
ALTER TABLE SATURN.SSRSRDF DISABLE CONSTRAINT FK1_SSRSRDF_INV_SSBSECT_KEY;
ALTER TABLE SATURN.SORCMJR disable constraints FK1_SORCMJR_INV_SOBCURR_KEY;
ALTER TABLE SATURN.SORMCRL DISABLE CONSTRAINTS FK1_SORMCRL_INV_SOBCURR_KEY;

-- 3. Borrado de Datos de todas las tablas que tiene CAMP_CODE
SELECT 'DELETE FROM ' ||x.owner||'.'|| x.TABLE_NAME || ' WHERE ' || x.column_name|| ' not in (' || '''CAL'',''YUM'',''JAM'',''ALP''' ||' );'
FROM DBA_TAB_COLUMNS x
WHERE x.column_name LIKE '%CAMP_CODE%'
order by x.table_name;

select * from dba_objects where object_name='SAVCCUR';

